### ISSUE TITLE
Fix calculations for 3d textures

### ISSUE THREAD

**Issue by ScanMountGoat** [ScanMountGoat/nutexb_swizzle#15]
The current implementation doesn't correctly calculate the block depth and block height for 3d textures (depth > 1). The block depth module also needs additional tests.

**Comment by ScanMountGoat** [comment]
This requires valid swizzled/deswizzled surface pairs for texture dimensions other than 16x16x16. This will require finding 3D textures in games other than Smash Ultimate, which only uses a single 3D texture size.

**Comment by encounter** [comment]
Metroid Prime Remastered has RGBA8 3D textures with dimensions 33x33x33 that I'm attempting to deswizzle.
tegra_swizzle expects 253440 bytes, whereas the texture data is 368640 bytes.

(The texture is a single mip, and the game's custom texture format specifies the mip0 size as 143748 bytes, corresponding to `33×33×33×4`, but the actual data is 368640 bytes. Possibly a bug in their tooling, but interesting.)

**Comment by ScanMountGoat** [comment]
> Metroid Prime Remastered has RGBA8 3D textures with dimensions 33x33x33 that I'm attempting to deswizzle. tegra_swizzle expects 253440 bytes, whereas the texture data is 368640 bytes.

Is that the only 3D texture you've found with different dimensions than 16x16x16? Thankfully, the only thing that really changes with different texture sizes is calculating the surface dimensions in bytes and figuring out the GOB ordering. I'll try and see if I can get more tests set up for 3D textures.

> (The texture is a single mip, and the game's custom texture format specifies the mip0 size as 143748 bytes, corresponding to `33×33×33×4`, but the actual data is 368640 bytes. Possibly a bug in their tooling, but interesting.)

This is not uncommon for Switch texture formats. I'm not sure what purpose it serves, but some formats specify the "unswizzled" size in the texture header. A size of 143748 bytes for 33x33x33x4 makes sense in this case.

**Comment by encounter** [comment]
> Is that the only 3D texture you've found with different dimensions than 16x16x16? 

Yes, all 3D textures in MP1R appear to be the same RGBA8 33x33x33.

> This is not uncommon for Switch texture formats. I'm not sure what purpose it serves, but some formats specify the "unswizzled" size in the texture header. A size of 143748 bytes for 33x33x33x4 makes sense in this case.

Makes sense! 

Happy to help test / provide more information if it'd be useful.

**Comment by ScanMountGoat** [comment]
You can try again on the latest commit by using git in the Cargo.toml. I've fixed the size calculations, but I'm not sure if the swizzling will work. `tegra_swizzle = { git = "https://github.com/ScanMountGoat/tegra_swizzle" }`

**Comment by encounter** [comment]
Works now! I'm not sure if the gray (actually transparent) parts are swizzling artifacts or intentional, but leaning towards intentional.

![Texture](https://user-images.githubusercontent.com/549122/223209067-0281034b-8245-49d7-aeb5-80e554e94b5a.png)

**Comment by ScanMountGoat** [comment]
> Works now! I'm not sure if the gray (actually transparent) parts are swizzling artifacts or intentional, but leaning towards intentional.
> 
> ![Texture](https://user-images.githubusercontent.com/549122/223209067-0281034b-8245-49d7-aeb5-80e554e94b5a.png)

I'm pretty confident that the swizzling is still incorrect. That texture looks like it should be similar to the one on the README of this repo. The black bars at different levels usually indicate that the swizzle code is copying 0's from padding bytes in the swizzled surface. You can see how the depth slices on the right half are not complete. 

Can you upload the swizzled texture in a zip file? I don't need the entire texture file. Just the image data in a .bin file works fine. I'll need to get proper test cases set up eventually using Ryujinx's output as a reference.

**Comment by encounter** [comment]
Sure, here's the original texture data: [tex.zip](https://github.com/ScanMountGoat/tegra_swizzle/files/10902266/tex.zip)

**Comment by ScanMountGoat** [comment]
This is what I get after putting together a simple CLI converter program using Ryujinx. I'll work on fixing the implementation in tegra_swizzle and let you know when it's ready for you to test.
![tex deswizzled](https://user-images.githubusercontent.com/23301691/223492685-2e3d3c11-ecda-49de-a6fe-1e8b32296fc4.png)

**Comment by ScanMountGoat** [comment]
This should be fixed on the latest commit. I've updated the implementation and added appropriate test cases. Please try again on the new commit and let me know if it's working for you. @encounter

**Comment by encounter** [comment]
Awesome! Just tested and it looks great. Thanks for the quick fix.

**Comment by ScanMountGoat** [comment]
Great. You can switch to version `0.3.1` from crates.io now.
