### ISSUE TITLE
Swizzle bit patterns typo?

### ISSUE THREAD

**Issue by fdwr** [ScanMountGoat/nutexb_swizzle#29]
Should the [Block 16 Swizzle Patterns](https://github.com/ScanMountGoat/tegra_swizzle/blob/b28e5efa59150c159aaa9303e5134f94f51e8573/swizzle.md#block-16-swizzle-patterns-bc2-bc3-bc5-bc6-bc7-r32g32b32a32_float) here...

https://github.com/ScanMountGoat/tegra_swizzle/blob/d2edff2083d07c26cb1917f8867b53263c5a06cd/swizzle.md?plain=1#L62-L65

...be this?

```diff
- 8 | 8 | 2 | 2 | 00000000000000100010 | 00000000000000100001
+ 8 | 8 | 2 | 2 | 00000000000000000010 | 00000000000000000001
- 16 | 16 | 4 | 4 | 00000000000000010010 | 00000000000000000101
+ 16 | 16 | 4 | 4 | 00000000000000001010 | 00000000000000000101
```

Otherwise the bits do not interleave.

**Comment by ScanMountGoat** [comment]
Good catch. I thought I had removed bit patterns from all the documentation, but it looks like I missed some. The actual swizzling function is defined in hardware docs as a function of x and y byte coordinates. The bit pattern trick doesn't work for tegra swizzling in general. I've still kept a link to the blog post because it's well written and does a good job of explaining possible implementations.

**Comment by fdwr** [comment]
> The actual swizzling function is defined in hardware docs

Ooh, do you have a searchable title to find this doc? I'm not finding good search results with "Tegra X1 TRM specification", and I'd love to read through it (amusing the highest search results are this repo 😉). Perhaps it's hidden somewhere inside the NVidia Developer website.

**Comment by ScanMountGoat** [comment]
It's the Tegra X1 technical reference manual (TRM). I reference it a few times in the source code. There are also comments indicating which parts are taken from reverse engineered driver code from Ryujinx. It should be page 1187 in the TRM for swizzling. I believe you need to create an nvidia developer account to access it, but it's also linked here: https://switchbrew.org/wiki/Tegra_X1

**Comment by fdwr** [comment]
Thanks - downloaded from NVidia's website after logging in as developer (page 1217 in the newer version). Cheers.
