### ISSUE TITLE
504x156 texture incorrect after deswizzle_surface?

### ISSUE THREAD

**Issue by gibbed** [ScanMountGoat/nutexb_swizzle#36]
I have some BC7 texture data which is `504`x`156`.

I'm calling `deswizzle_surface` like so: `deswizzle_surface(504, 156, 1, ..., block4x4, 16, 16, 1, 1)`.

Unfortunately, this results in a texture that is not quite so right:

![bt_merits_words01](https://github.com/user-attachments/assets/1aee2ba7-c469-4cc3-9e29-f01dc65c00ac)

I know what it's supposed to look like from the PC version:

![bt_merits_words01](https://github.com/user-attachments/assets/c0d86dbe-18e6-451f-b185-2dec4c62e050)

I _don't_ think I'm calling `deswizzle_surface` incorrectly here; the correct amount of source data is being passed in (matches what is in the file) and the expected amount of data is being given in the destination. I will add that I'm using the FFI interface from C# bindings I put together.

Texture data so far seems to be coming out correctly for texture data that is either POT or have a NPOT width and POT height (ie, `504`x`64`).

**Comment by gibbed** [comment]
I've found that calling `deswizzle_surface` with the same arguments, same source data, but with a `height` of `128` results in a correct texture data with the bottom cropped off.

There is actual pixel data on the bottom of the texture data so I don't think this is an issue of a funny business with the texture dimensions.

![bt_merits_words01](https://github.com/user-attachments/assets/21d00e1a-a714-47c2-b272-ea92bc88529a)

Trying heights of `160` (aligned to 32) or `256` (next POT) did not work however.

**Comment by ScanMountGoat** [comment]
I'll need to see the texture file itself to try and look into this. Non power of two or odd dimensions shouldn't cause any problems.

**Comment by gibbed** [comment]
Here's the texture file, texture data starts at `0x50` to the remainder of the file.

*link to sample removed*

`swizzled_surface_size` correctly gives me a size of `0x20000` bytes.

**Comment by ScanMountGoat** [comment]
Calculate the block height parameter with `block_height_mip0`. Some formats store the block height explicitly. It's almost always calculated by the driver from my experience. It's working for me with the calculated block height of 4.
https://docs.rs/tegra_swizzle/latest/tegra_swizzle/fn.block_height_mip0.html.

**Comment by gibbed** [comment]
~~Calling `block_height_mip0(156)` returns `16` for me, rather than `4`?~~

I'll double-check to be sure, but you're right in that passing `4` in works as expected.

edit: I see, I misunderstood the comments I read in the code, your link to the documentation clarifies the problem.

Thanks!

**Comment by ScanMountGoat** [comment]
Glad it's working for you now. Let me know if you run into any more problems with this code in the future.

**Comment by gibbed** [comment]
Seems to be good now; interesting that my misuse of `block_height_mip0` wasn't producing any artifacts for many other textures.
